# Etapa 1: Instala todas las dependencias (usa cache)
FROM node:24-alpine3.22 AS deps
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Etapa 2: Build
FROM node:24-alpine3.22 AS build
WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

# ✅ Generar cliente de Prisma
RUN npx prisma generate

# Compilar la app
RUN yarn run build

# Etapa 3: Producción (solo dependencias necesarias)
FROM node:24-alpine3.22 AS prod
WORKDIR /usr/src/app

# Copiar archivos mínimos
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile && yarn cache clean

# Copiar el build compilado y el cliente de Prisma
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules/.prisma ./node_modules/.prisma

ENV NODE_ENV=production
USER node
EXPOSE 3000

CMD ["node", "dist/main.js"]
